config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :tests
  root "entries#index"
  resources :entries do
    resources :attachments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  belongs_to :entry

  mount_uploader :file, AttachmentUploader

  validates :name, presence: true
  validates :extension, presence: true
  validates :size, presence: true
  validates :file, presence: true

  before_validation(on: :create) {
    self.name = self.file.file.filename if self.file.present?
    self.extension = self.file.file.extension.downcase if self.file.present?
    self.size = self.file.file.size if self.file.present?
  }

  def image?
    ["png", "jpg", "gif", "jpeg"].include?(extension)
  end

end

app/models/entry.rb
class Entry < ApplicationRecord

  has_many :attachments

  validates :date, presence: true
  validates :content, presence: true

  scope :ordered, -> { order(date: :asc) }

  def title
    "##{id}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  before_action { params[:entry_id] && @entry = Entry.find(params[:entry_id]) }
  before_action { params[:id] && @attachment = @entry.attachments.find(params[:id]) }

  def index
    @attachments = @entry.attachments.all
  end

  def show
  end

  def new
    @attachment = Attachment.new
    render action: "form"
  end

  def edit
    render action: "form"
  end

  def create
    @attachment = @entry.attachments.build(safe_params)
    if @attachment.save
      redirect_to @entry
    else
      render :new
    end
  end

  def update
    if @attachment.update_attributes(safe_params)
      redirect_to @entry
    else
      render :new
    end
  end

  def destroy
    @attachment.destroy
    redirect_to @entry
  end

  private

  def safe_params
    params.require(:attachment).permit(:file)
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action { params[:id] && @entry = Entry.find(params[:id]) }

  def index
    # @entries = Entry.all.order(date: :desc)

    params[:start] ? st = Date.parse(params[:start]) : st = Date.today
    params[:end] ? et = Date.parse(params[:end]).end_of_day : et = Date.today.end_of_day

    @entries = Entry.ordered.where(date: st..et)
  end

  def show
    @attachments = @entry.attachments.load
    render layout: false
  end

  def new
    @entry = Entry.new
    render action: "form"
  end

  def edit
    render action: "form"
  end

  def create
    @entry = Entry.new(safe_params)
    if @entry.save
      redirect_to entries_path
    else
      render action: "form"
    end
  end

  def update
    if @entry.update_attributes(safe_params)
      redirect_to entries_path
    else
      render action: "form"
    end
  end

  private

  def safe_params
    params.require(:entry).permit(:date, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attachments/form.html.haml
= bootstrap_form_for @attachment, url: [@entry, @attachment] do |f|
  = f.file_field :file
  = f.submit

app/views/entries/_modal.html.haml
.modal.fade#createEntryModal
  .modal-dialog
    .modal-content
      .modal-header
        %button{type: "button", class: "close", data: {dismiss: "modal"}} &times;
        %h4.modal-title Create Entry

      .modal-body
        = bootstrap_form_for Entry.new do |f|
          = f.text_field :date
          = f.text_area :content, autofocus: true, rows: 10
          = f.submit

app/views/entries/form.html.haml
= bootstrap_form_for @entry do |f|
  = f.text_field :date
  = f.text_area :content, autofocus: true, rows: 10
  = f.submit

app/views/entries/index.html.haml
.page-header
  .pull-right
    = link_to "New Entry", new_entry_path, class: "btn btn-primary"
  %h1 Entries

#calendar

= render "entries/modal"

app/views/entries/show.html.haml
%h3 Entry ##{@entry.id} for #{@entry.date.to_s(:long)}

%hr

= simple_format @entry.content

%hr

- if @attachments.present?
  - @attachments.each do |attach|
    %ul
    - if attach.image?
      %li
        = link_to image_tag(attach.file.url(:thumb)), attach.file.url
        = link_to fa_icon("trash"), entry_attachment_path(@entry, attach), method: :delete, data: {confirm: "Are you sure?"}
    - else
      %li
        = link_to attach.name, attach.file.url
        = link_to fa_icon("trash"), entry_attachment_path(@entry, attach), method: :delete, data: {confirm: "Are you sure?"}

  %hr

= link_to "Edit", edit_entry_path(@entry), class: "btn btn-primary btn-sm"
= link_to "New Attachment", new_entry_attachment_path(@entry), class: "btn btn-primary btn-sm"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Journal
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

    %meta{content: "width=device-width, user-scalable=no,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0", name: "viewport"}
  %body
    %nav.navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Journal", root_path, class: "navbar-brand"
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            = active_link_to "Entries", entries_path, wrap_tag: :li#, active: :exact

    .container.content
      = display_flash
      = yield